/**
 * GitHub Issue Template — GitHub-flavored Markdown for issue bodies
 *
 * Optimized for pasting directly into GitHub issue descriptions.
 * Uses task lists, collapsible details, and GFM formatting.
 */

import type { OutputTemplate, TemplateContext, TemplateOutput } from './types';
import {
  formatTimestamp,
  formatDate,
  computeSessionDuration,
  generateSegmentTitle,
  computeRelativeFramePath,
  mapFramesToSegments,
} from './helpers';
import { renderMarkedIssuesMarkdown } from '../MarkedIssueReportBuilder';

export const githubIssueTemplate: OutputTemplate = {
  name: 'github-issue',
  description: 'GitHub-flavored Markdown optimized for issue bodies with task lists and collapsible details',
  fileExtension: '.md',

  render(context: TemplateContext): TemplateOutput {
    const { result, sessionDir, timestamp } = context;
    const { transcriptSegments, extractedFrames, markedIssues = [] } = result;
    const ordinaryFrames = extractedFrames.filter((frame) => !frame.markedIssueId);
    const sessionTimestamp = formatDate(new Date(timestamp ?? Date.now()));
    const duration = computeSessionDuration(transcriptSegments);

    let md = `## Feedback Report\n\n`;
    md += `> Captured by [markupR](https://markupr.com) on ${sessionTimestamp}\n`;
    md += `> ${transcriptSegments.length} segments | ${extractedFrames.length} frames | Duration: ${duration}\n\n`;
    if (markedIssues.length > 0) {
      md += renderMarkedIssuesMarkdown(markedIssues, './screenshots');
    }

    if (transcriptSegments.length === 0) {
      md += `_No feedback was captured during this recording._\n`;
      return { content: md, fileExtension: '.md' };
    }

    // Action items as task list
    md += `### Action Items\n\n`;
    for (const segment of transcriptSegments) {
      const title = generateSegmentTitle(segment.text);
      md += `- [ ] ${title}\n`;
    }
    md += `\n`;

    // Details for each segment
    md += `### Details\n\n`;
    const segmentFrameMap = mapFramesToSegments(transcriptSegments, ordinaryFrames);

    for (let i = 0; i < transcriptSegments.length; i++) {
      const segment = transcriptSegments[i];
      const formattedTime = formatTimestamp(segment.startTime);
      const title = generateSegmentTitle(segment.text);

      md += `<details>\n`;
      md += `<summary><strong>[${formattedTime}] ${title}</strong></summary>\n\n`;
      md += `${segment.text}\n\n`;

      const frames = segmentFrameMap.get(i);
      if (frames && frames.length > 0) {
        for (const frame of frames) {
          const relativePath = computeRelativeFramePath(frame.path, sessionDir);
          md += `![Screenshot](${relativePath})\n\n`;
        }
      }

      md += `</details>\n\n`;
    }

    md += `---\n_Generated by [markupR](https://markupr.com)_\n`;

    return { content: md, fileExtension: '.md' };
  },
};
