/**
 * Jira Template — Jira Wiki Markup
 *
 * Produces Jira wiki markup with {code} blocks, panels, and tables.
 * Compatible with Jira Cloud and Server issue descriptions.
 */

import type { OutputTemplate, TemplateContext, TemplateOutput } from './types';
import {
  formatTimestamp,
  formatDate,
  computeSessionDuration,
  generateSegmentTitle,
  computeRelativeFramePath,
  mapFramesToSegments,
} from './helpers';
import { renderMarkedIssuesJira } from '../MarkedIssueReportBuilder';
import { PUBLIC_BRAND_NAME, PUBLIC_WEBSITE_URL } from '../../../shared/publicBrand';

export const jiraTemplate: OutputTemplate = {
  name: 'jira',
  description: 'Jira wiki markup with panels, tables, and {code} blocks',
  fileExtension: '.jira',

  render(context: TemplateContext): TemplateOutput {
    const { result, sessionDir, timestamp } = context;
    const { transcriptSegments, extractedFrames, markedIssues = [] } = result;
    const ordinaryFrames = extractedFrames.filter((frame) => !frame.markedIssueId);
    const sessionTimestamp = formatDate(new Date(timestamp ?? Date.now()));
    const duration = computeSessionDuration(transcriptSegments);

    let content = `h1. Feedback Report\n\n`;

    content += `{panel:title=Session Info|borderStyle=solid|borderColor=#ccc}\n`;
    content += `*Captured:* ${sessionTimestamp}\n`;
    content += `*Segments:* ${transcriptSegments.length} | *Frames:* ${extractedFrames.length} | *Duration:* ${duration}\n`;
    content += `{panel}\n\n`;
    if (markedIssues.length > 0) {
      content += renderMarkedIssuesJira(markedIssues);
    }

    if (transcriptSegments.length === 0) {
      content += `_No feedback was captured during this recording._\n`;
      return { content, fileExtension: '.jira' };
    }

    // Summary table
    content += `h2. Summary\n\n`;
    content += `||#||Timestamp||Feedback||\n`;
    for (let i = 0; i < transcriptSegments.length; i++) {
      const segment = transcriptSegments[i];
      const formattedTime = formatTimestamp(segment.startTime);
      const title = generateSegmentTitle(segment.text);
      content += `|${i + 1}|${formattedTime}|${title}|\n`;
    }
    content += `\n`;

    // Detail sections
    content += `h2. Details\n\n`;
    const segmentFrameMap = mapFramesToSegments(transcriptSegments, ordinaryFrames);

    for (let i = 0; i < transcriptSegments.length; i++) {
      const segment = transcriptSegments[i];
      const formattedTime = formatTimestamp(segment.startTime);
      const title = generateSegmentTitle(segment.text);

      content += `h3. \\[${formattedTime}\\] ${title}\n\n`;
      content += `{quote}\n${segment.text}\n{quote}\n\n`;

      const frames = segmentFrameMap.get(i);
      if (frames && frames.length > 0) {
        for (const frame of frames) {
          const relativePath = computeRelativeFramePath(frame.path, sessionDir);
          content += `!${relativePath}|thumbnail!\n\n`;
        }
      }
    }

    content += `----\n_Generated by [${PUBLIC_BRAND_NAME}|${PUBLIC_WEBSITE_URL}]_\n`;

    return { content, fileExtension: '.jira' };
  },
};
