/**
 * Markdown Template — Default output format
 *
 * Produces identical output to MarkdownGenerator.generateFromPostProcess().
 * This is the reference template that all others derive context from.
 */

import type { OutputTemplate, TemplateContext, TemplateOutput } from './types';
import {
  formatTimestamp,
  formatDate,
  computeSessionDuration,
  wrapTranscription,
  generateSegmentTitle,
  computeRelativeFramePath,
  mapFramesToSegments,
} from './helpers';
import { renderMarkedIssuesMarkdown } from '../MarkedIssueReportBuilder';
import { PUBLIC_BRAND_NAME, PUBLIC_WEBSITE_URL } from '../../../shared/publicBrand';

const REPORT_SUPPORT_LINE = '*If this report saved you time, support development: [Ko-fi](https://ko-fi.com/eddiesanjuan)*';

export const markdownTemplate: OutputTemplate = {
  name: 'markdown',
  description: 'Default Markdown format — AI-ready, llms.txt-inspired structured document',
  fileExtension: '.md',

  render(context: TemplateContext): TemplateOutput {
    const { result, sessionDir, timestamp } = context;
    const { transcriptSegments, extractedFrames, markedIssues = [] } = result;
    const ordinaryFrames = extractedFrames.filter((frame) => !frame.markedIssueId);
    const sessionTimestamp = formatDate(new Date(timestamp ?? Date.now()));

    const sessionDuration = computeSessionDuration(transcriptSegments);

    let md = `# ${PUBLIC_BRAND_NAME} Session — ${sessionTimestamp}\n`;
    md += `> Segments: ${transcriptSegments.length} | Frames: ${extractedFrames.length} | Duration: ${sessionDuration}\n\n`;
    if (markedIssues.length > 0) {
      md += renderMarkedIssuesMarkdown(markedIssues, './screenshots');
    }

    if (transcriptSegments.length === 0) {
      md += `_No speech was detected during this recording._\n\n`;
      md += `---\n*Generated by [${PUBLIC_BRAND_NAME}](${PUBLIC_WEBSITE_URL})*\n${REPORT_SUPPORT_LINE}\n`;
      return { content: md, fileExtension: '.md' };
    }

    md += `## Transcript\n\n`;

    const segmentFrameMap = mapFramesToSegments(transcriptSegments, ordinaryFrames);

    for (let i = 0; i < transcriptSegments.length; i++) {
      const segment = transcriptSegments[i];
      const formattedTime = formatTimestamp(segment.startTime);
      const title = generateSegmentTitle(segment.text);

      md += `### [${formattedTime}] ${title}\n`;
      md += `> ${wrapTranscription(segment.text)}\n\n`;

      const frames = segmentFrameMap.get(i);
      if (frames && frames.length > 0) {
        for (const frame of frames) {
          const frameTimestamp = formatTimestamp(frame.timestamp);
          const relativePath = computeRelativeFramePath(frame.path, sessionDir);
          md += `![Frame at ${frameTimestamp}](${relativePath})\n\n`;
          const cursor = frame.captureContext?.cursor
            ? `Cursor: ${Math.round(frame.captureContext.cursor.x)}, ${Math.round(frame.captureContext.cursor.y)}`
            : undefined;
          const app = frame.captureContext?.activeWindow?.appName || frame.captureContext?.activeWindow?.sourceName;
          const focus = frame.captureContext?.focusedElement?.textPreview
            || frame.captureContext?.focusedElement?.label
            || frame.captureContext?.focusedElement?.role;
          const contextLine = [cursor, app ? `App: ${app}` : undefined, focus ? `Focus: ${focus}` : undefined]
            .filter(Boolean)
            .join(' | ');
          if (contextLine) {
            md += `> ${contextLine}\n\n`;
          }
        }
      }
    }

    md += `---\n*Generated by [${PUBLIC_BRAND_NAME}](${PUBLIC_WEBSITE_URL})*\n${REPORT_SUPPORT_LINE}\n`;

    return { content: md, fileExtension: '.md' };
  },
};
