/**
 * Optional Traditional Chinese interface translation catalog.
 * English source labels are retained by the shared UI localizer.
 */
import type { UiTranslationCatalog } from './i18n/catalogs';

const EXACT_TRANSLATIONS: Record<string, string> = {
  'Interface language': '介面語言',
  'English by default. Changes apply immediately.': '預設為英文。變更會立即套用。',
  'Recording Active': '正在錄製',
  'Latest Report Path': '最新報告位置',
  'Session Recording': '工作階段錄影',
  'Narration Audio': '旁白音訊',
  'Recent Captures': '最近的擷取內容',
  'No captures yet. Run a session to see them here.': '目前還沒有擷取內容。開始一次工作階段後，內容會顯示在這裡。',
  'No captures yet. Run a session and it will appear here.': '目前還沒有擷取內容。開始一次工作階段後，內容會顯示在這裡。',
  'Open Settings': '開啟設定',
  Settings: '設定',
  'Open Session History': '開啟工作階段紀錄',
  'Session History': '工作階段紀錄',
  'Start Session': '開始工作階段',
  'Pause Session': '暫停工作階段',
  'Resume Session': '繼續工作階段',
  'Stop Session': '停止工作階段',
  'Capture Screenshot': '擷取螢幕畫面',
  'Add OpenAI Key': '新增 OpenAI 金鑰',
  'Open Report Settings': '開啟報告設定',
  Undo: '復原',
  Clear: '清除',
  'Done · Esc': '完成 · Esc',
  'Something went wrong': '發生錯誤',
  'Error Details': '錯誤詳細資料',
  'Recent feedback:': '最近的回饋：',
  'Esc to discard': '按 Esc 捨棄',
  Preview: '預覽',
  'Export Feedback': '匯出回饋',
  'Exported to': '已匯出至',
  'Choose Format': '選擇格式',
  Options: '選項',
  'Include Images': '包含圖片',
  Theme: '主題',
  'Exporting...': '匯出中……',
  'Export in progress...': '正在匯出……',
  'Exported!': '已匯出！',
  'Press keys...': '請按下按鍵……',
  'Record and narrate your walkthrough.': '錄製操作流程並加入旁白。',
  'Mark shots when needed. Markers confirm instantly.': '需要時標記畫面，標記會立即確認。',
  'Stop recording. AI aligns transcript + frames into a report.': '停止錄製，AI 會將逐字稿與畫面整理成報告。',
  'Microphone Access': '麥克風權限',
  'Speak to test your microphone': '說話以測試麥克風',
  'Permission Denied': '權限遭拒',
  'Open System Settings': '開啟系統設定',
  'Toggle the switch ON': '將開關切換為開啟',
  'Check Again': '再次檢查',
  'Screen Recording': '螢幕錄製',
  'Manual Setup Required': '需要手動設定',
  "API key verified! You're ready to go.": 'API 金鑰已驗證！可以開始使用。',
  "You're All Set!": '全部準備完成！',
  'Voice transcription ready': '語音轉錄已準備完成',
  'Each marked screen is saved as a separate issue': '每個標記的畫面都會另存為一個問題',
  'Each issue keeps its matching narration and screenshot': '每個問題都會保留對應的旁白與螢幕截圖',
  'Monitor Arrangement': '螢幕排列',
  'Select Window to Capture': '選擇要擷取的視窗',
  Screens: '螢幕',
  Windows: '視窗',
  'No sources available': '沒有可用的來源',
  'Update Available': '有可用更新',
  'Downloading Update': '正在下載更新',
  'Please wait': '請稍候',
  'Update Ready': '更新已準備完成',
  'Update Failed': '更新失敗',
  Custom: '自訂',
  'API key verified and saved securely.': 'API 金鑰已驗證並安全儲存。',
  'Loading transcription options...': '正在載入轉錄選項……',
  'Transcription Service': '轉錄服務',
  Active: '使用中',
  'Download required (~75MB) for local transcription': '本機轉錄需要下載約 75 MB 的模型',
  'Markdown Preview': 'Markdown 預覽',
  'Open Folder': '開啟資料夾',
  Copy: '複製',
  Close: '關閉',
  'No feedback items': '沒有回饋項目',
  'Start a new recording to capture feedback': '開始新的錄製以擷取回饋',
  Retry: '重試',
  Dismiss: '略過',
  Export: '匯出',
  Delete: '刪除',
  'Newest first': '最新的在前',
  'Oldest first': '最舊的在前',
  'Session actions': '工作階段操作',
  General: '一般',
  Recording: '錄製',
  Appearance: '外觀',
  Hotkeys: '快速鍵',
  Advanced: '進階',
  'No countdown': '不倒數',
  '3 seconds': '3 秒',
  '5 seconds': '5 秒',
  'System Default': '系統預設',
  '(Default)': '（預設）',
  System: '系統',
  Dark: '深色',
  Light: '淺色',
  'Start/Stop Recording': '開始／停止錄製',
  'Manual Screenshot': '手動擷取螢幕畫面',
  'Pause/Resume': '暫停／繼續',
  'Checking bridge…': '正在檢查橋接程式……',
  'Checking this Mac.': '正在檢查這台電腦。',
  Connected: '已連線',
  'Bridge offline': '橋接程式離線',
  'Update required': '需要更新',
  'Pairing rejected': '配對遭拒',
  'Not paired': '尚未配對',
  'Built in': '內建',
  'Pairing token': '配對權杖',
  'Paste the token from step 3': '貼上第 3 步取得的權杖',
  'OpenAI Audio Transcription': 'OpenAI 音訊轉錄',
  'Anthropic Analysis': 'Anthropic 分析',
  'Export Settings': '匯出設定',
  'Save your settings to a file': '將設定儲存至檔案',
  'Load settings from a file': '從檔案載入設定',
  'Report generation provider': '報告產生服務',
  'Codex CLI': 'Codex CLI',
  'Claude Code CLI': 'Claude Code CLI',
  OpenCode: 'OpenCode',
  'Cursor Agent CLI': 'Cursor Agent CLI',
  'Qwen Code': 'Qwen Code',
  Goose: 'Goose',
  Amp: 'Amp',
  'Kiro CLI': 'Kiro CLI',
  Aider: 'Aider',
  Ollama: 'Ollama',
  'LM Studio': 'LM Studio',
  'Anthropic API': 'Anthropic API',
  'Local Rules': '本機規則',
  'Use your installed Codex CLI and existing ChatGPT login.': '使用已安裝的 Codex CLI 與現有 ChatGPT 登入狀態。',
  'Use your installed and signed-in Claude Code CLI.': '使用已安裝且已登入的 Claude Code CLI。',
  'Generate reports with your configured OpenCode providers.': '使用已設定的 OpenCode 服務產生報告。',
  'Generate reports with Cursor Agent in read-only Ask mode.': '使用 Cursor Agent 的唯讀 Ask 模式產生報告。',
  'Use Qwen Code in safe, non-interactive mode.': '以安全的非互動模式使用 Qwen Code。',
  'Generate reports with your configured Goose CLI model.': '使用已設定的 Goose CLI 模型產生報告。',
  'Use your installed and signed-in Amp CLI.': '使用已安裝且已登入的 Amp CLI。',
  'Generate reports with Kiro in non-interactive mode.': '以非互動模式使用 Kiro 產生報告。',
  'Use Aider in dry-run mode without modifying your files.': '以預演模式使用 Aider，不修改檔案。',
  'Generate reports with a model served locally by Ollama.': '使用 Ollama 在本機提供的模型產生報告。',
  'Generate reports with an LM Studio local server model.': '使用 LM Studio 本機伺服器的模型產生報告。',
  'Use an Anthropic API key stored securely by MarkuprPlus.': '使用由 MarkuprPlus 安全儲存的 Anthropic API 金鑰。',
  'Build a report locally without an AI provider.': '不使用 AI 服務，在本機建立報告。',
  Save: '儲存',
  Cancel: '取消',
  Back: '返回',
  Next: '下一步',
  Continue: '繼續',
  Skip: '略過',
  Start: '開始',
  Stop: '停止',
  Pause: '暫停',
  Resume: '繼續',
  Record: '錄製',
  Report: '報告',
  Feedback: '回饋',
  Microphone: '麥克風',
  Screen: '螢幕',
  Audio: '音訊',
  Language: '語言',
  'Output Directory': '輸出資料夾',
  'Accent Color': '強調色',
  Saved: '已儲存',
  Saving: '儲存中……',
  'Unable to save': '無法儲存',
  'AI Setup': 'AI 設定',
  'Back to MarkuprPlus': '返回 MarkuprPlus',
  'Settings content': '設定內容',
  'Show more settings sections': '顯示更多設定區段',
  'Show previous settings sections': '顯示上一個設定區段',
  'Reset All to Defaults': '全部重設為預設值',
  Browse: '瀏覽',
  'Browse...': '瀏覽……',
  'Where your feedback sessions are saved': '回饋工作階段的儲存位置',
  'Screenshots and markdown files will be saved here': '螢幕截圖與 Markdown 檔案會儲存在這裡',
  'Launch at Login': '登入時啟動',
  'Start MarkuprPlus automatically when you log in': '登入時自動啟動 MarkuprPlus',
  'Customize how recording sessions work': '自訂錄製工作階段的運作方式',
  'Countdown Before Recording': '錄製前倒數',
  'Give yourself time to prepare': '預留準備時間',
  'Show Recording HUD': '顯示錄製資訊面板',
  'Display mic activity and shortcut hints while recording': '錄製時顯示麥克風活動與快速鍵提示',
  'Show Audio Waveform': '顯示音訊波形',
  'Visual feedback of your voice levels': '顯示音量大小的視覺回饋',
  'Select which microphone to use for voice capture': '選擇用於錄製語音的麥克風',
  'Pause Threshold': '暫停判定時間',
  'How long to pause before capturing a screenshot': '暫停多久後擷取螢幕畫面',
  'Minimum Time Between Captures': '擷取間隔下限',
  'Prevent too many screenshots in quick succession': '避免在短時間內擷取過多螢幕畫面',
  'Choose how MarkuprPlus looks': '選擇 MarkuprPlus 的外觀',
  'Theme Mode': '主題模式',
  'Match your system or choose a specific theme': '跟隨系統或選擇特定主題',
  'Used for buttons, links, and highlights': '用於按鈕、連結與醒目提示',
  'Recording Session': '錄製工作階段',
  'Start Recording': '開始錄製',
  'Customize global hotkeys for MarkuprPlus': '自訂 MarkuprPlus 的全域快速鍵',
  'Toggle recording on and off': '切換錄製的開始與停止',
  'Capture a screenshot immediately': '立即擷取螢幕畫面',
  'Temporarily pause active capture': '暫時暫停目前的擷取',
  'Choose the provider and model that turn each capture into a structured report.': '選擇將每次擷取內容整理成結構化報告的服務與模型。',
  'Ready · no credentials required': '準備完成 · 不需要認證資料',
  'Checking availability…': '正在檢查可用性……',
  'Ready · ': '準備完成 · ',
  'Not ready': '尚未準備完成',
  Recommended: '推薦',
  Selected: '已選取',
  'Report model': '報告模型',
  'Only models discovered from the local provider can be selected.': '只能選取從本機服務找到的模型。',
  'Leave blank for the provider default, choose a suggestion, or enter a model ID.': '留白即可使用服務預設值，也可以選擇建議項目或輸入模型 ID。',
  'Refreshing…': '重新整理中……',
  'Refresh providers': '重新整理服務',
  Local: '本機',
  Cloud: '雲端',
  'Local transcription ready': '本機轉錄已準備完成',
  'Local transcription needs repair': '本機轉錄需要修復',
  'Checking local transcription…': '正在檢查本機轉錄……',
  'Whisper runs automatically after recording and does not generate the report.': 'Whisper 會在錄製結束後自動執行，負責語音轉錄，不負責產生報告。',
  'Download the managed ': '下載管理中的 ',
  ' model for automatic local transcription.': ' 模型以自動進行本機轉錄。',
  'Checking the managed local transcription model.': '正在檢查管理中的本機轉錄模型。',
  'Downloading…': '下載中……',
  'Repair local transcription': '修復本機轉錄',
  'Keys are stored locally and only used for their named service.': '金鑰會儲存在本機，只會用於對應的服務。',
  'Optional cloud transcription': '選用的雲端轉錄',
  'Optional when local transcription is available': '本機轉錄可用時可省略',
  'Used for reliable post-session narration transcription when local models are unavailable.': '本機模型無法使用時，用於在工作階段結束後可靠地轉錄旁白。',
  'Required only when Anthropic API is selected above': '只有在上方選擇 Anthropic API 時才需要',
  'Used to generate structured, agent-ready markdown insights from your capture session.': '用來將你的擷取工作階段整理成結構化、可供 AI Agent 使用的 Markdown 洞察。',
  'Used only for Anthropic analysis': '只用於 Anthropic 分析',
  'Debug Mode': '除錯模式',
  'Enable verbose logging for troubleshooting': '啟用詳細記錄以協助排除問題',
  'Keep Audio Backups': '保留音訊備份',
  'Save audio recordings alongside transcriptions': '將音訊錄音與轉錄檔一起儲存',
  'Delete all sessions, screenshots, and reset settings': '刪除所有工作階段與螢幕截圖，並重設設定',
  'Clear All Data': '清除所有資料',
  'Take a quick annotated screenshot': '快速擷取並標註螢幕畫面',
  'Conflict with:': '與下列項目衝突：',
  'Conflicts with:': '與下列項目衝突：',
  Retest: '再次測試',
  'Test Connection': '測試連線',
  'Import Settings': '匯入設定',
  Import: '匯入',
  'Clear All Data (Enter)': '清除所有資料（Enter）',
  'AI-ready report': 'AI 可用報告',
  'Transcript Ready': '轉錄已準備完成',
  'shots marked': '個已標記畫面',
  'Session paused': '工作階段已暫停',
  'Mic is active': '麥克風使用中',
  'Listening for narration': '正在聆聽旁白',
  'Mark Shot: ': '標記畫面：',
  'Stop: ': '停止：',
  'Pause: ': '暫停：',
  'Manual shots are confirmed instantly above. After stop, AI analyzes your transcript + screen frames and assembles an AI-ready report.': '上方的手動畫面標記會立即確認。停止後，AI 會分析逐字稿與螢幕畫面，整理成可供 AI 使用的報告。',
  'Processing your recording': '正在處理你的錄製內容',
  'Preparing...': '準備中……',
  'Copy Path': '複製路徑',
  'Copy Recording Path': '複製錄影路徑',
  'Copy Audio Path': '複製音訊路徑',
  'Open Review Editor': '開啟回饋編輯器',
  Refresh: '重新整理',
  'Feedback Session': '回饋工作階段',
  items: '個項目',
  shots: '個畫面',
  'Copy File Path': '複製檔案路徑',
  'Mic activity is monitored live; narration is transcribed after recording completes.': '麥克風活動會即時監測；錄製完成後才會轉錄旁白。',
  'Global hotkey: ': '全域快速鍵：',
  'starts or stops the loop.': '開始或停止循環。',
  'Preparing Session': '正在準備工作階段',
  'Initializing microphone capture and session recording.': '正在初始化麥克風擷取與工作階段錄製。',
  'Recording Live': '正在錄製',
  'Session paused. Resume to continue capturing screen and narration.': '工作階段已暫停。繼續後會恢復螢幕與旁白擷取。',
  'Mark shots while you narrate. After stop, AI aligns frames + transcript and assembles an AI-ready report.': '講述時標記畫面。停止後，AI 會對齊畫面與逐字稿，整理成可供 AI 使用的報告。',
  'Processing Your Recording': '正在處理你的錄製內容',
  'Report Ready': '報告已準備完成',
  'Markdown path copied to your clipboard.': 'Markdown 路徑已複製到剪貼簿。',
  'An unexpected error interrupted this capture.': '這次擷取遇到未預期的錯誤而中斷。',
  'Ready To Capture': '準備開始擷取',
  'Recording works now. Add an OpenAI API key or repair the managed local transcription model for automatic narration transcription.': '目前可以錄製。新增 OpenAI API 金鑰，或修復管理中的本機轉錄模型，即可自動轉錄旁白。',
  'Press Cmd+Shift+F to start a fresh feedback pass.': '按下 Cmd+Shift+F 開始新的回饋記錄。',
  Output: '輸出',
  Startup: '啟動',
  'Audio Input': '音訊輸入',
  'Screenshot Timing': '螢幕截圖時機',
  'Recording Behavior': '錄製行為',
  'Quick Reference': '快速參考',
  'CLI Integrations': 'CLI 整合',
  'Report Generation': '報告產生',
  'Report Generation (Optional)': '報告產生（選用）',
  'Local Transcription': '本機轉錄',
  Credentials: '認證資料',
  'OpenAI API Key': 'OpenAI API 金鑰',
  'Anthropic API Key': 'Anthropic API 金鑰',
  'Debug & Backup': '除錯與備份',
  'Settings Management': '設定管理',
  'Danger Zone': '危險區域',
  'Review Editor': '回饋編輯器',
  'Unsaved changes': '尚未儲存的變更',
  'Transcript results': '轉錄結果',
  'Close screenshot preview': '關閉螢幕截圖預覽',
  'Screenshot preview': '螢幕截圖預覽',
  'Feedback items list': '回饋項目清單',
  'Keyboard Shortcuts': '鍵盤快速鍵',
  'Select a customizable shortcut to rebind it': '選擇要重新設定的快速鍵',
  'Search shortcuts...': '搜尋快速鍵……',
  'Clear shortcut search': '清除快速鍵搜尋',
  'Saving shortcut': '正在儲存快速鍵',
  'Setup progress': '設定進度',
  'Settings sections': '設定區段',
  'Recording in progress': '錄製進行中',
  'Marked issues saved separately in this session': '標記的問題會在此工作階段中分開儲存',
  'Annotation directions': '標註操作說明',
  'Live recording annotation layer': '即時錄製標註圖層',
  'Annotation tools': '標註工具',
  'Move over a window and click to record only that application.': '將滑鼠移到視窗上並點擊，只錄製該應用程式。',
  'Drag any area on this display. Release to start recording.': '在這個螢幕上拖曳選取區域，放開後開始錄製。',
  'Click anywhere to record this entire display.': '點擊任意位置以錄製整個螢幕。',
  'That source is no longer available.': '這個來源已無法使用。',
  'Unable to change capture mode.': '無法變更擷取模式。',
  'Choose what MarkuprPlus should record': '選擇 MarkuprPlus 要錄製的內容',
  'Window  W': '視窗  W',
  'Region  R': '區域  R',
  'Full Screen  S': '全螢幕  S',
  'Cancel  Esc': '取消  Esc',
  'Preparing capture choices…': '正在準備擷取選項……',
  'This capture overlay is no longer active.': '這個擷取浮層已不再作用。',
  'Unable to load capture controls.': '無法載入擷取控制項。',
  Arrow: '箭頭',
  Circle: '圓形',
  Rectangle: '矩形',
  Freehand: '自由繪製',
  Red: '紅色',
  Blue: '藍色',
  Yellow: '黃色',
  Green: '綠色',
  White: '白色',
  'Undo (Z)': '復原（Z）',
  'Redo (Y)': '重做（Y）',
  'Clear All (C)': '全部清除（C）',
  'Cancel (Escape)': '取消（Escape）',
  'Save (Enter)': '儲存（Enter）',
  'Enter project name...': '輸入專案名稱……',
  'Enter feedback text...': '輸入回饋文字……',
  'Select output directory...': '選擇輸出資料夾……',
  Hide: '隱藏',
  Show: '顯示',
  'Reset section to defaults': '將此區段重設為預設值',
  'Choose accent color': '選擇強調色',
  'Choose a custom accent color': '選擇自訂強調色',
  'Custom color': '自訂顏色',
  'Open session': '開啟工作階段',
  'More actions for session': '更多工作階段操作',
  'Clear session search': '清除工作階段搜尋',
  'Feedback actions for': '的回饋操作',
  'More actions for feedback': '更多回饋操作',
  'Click to view full size': '點擊檢視完整大小',
  'Complete a feedback session before exporting. Your finished report will be available here.': '完成回饋工作階段後才能預覽匯出內容。完成的報告會顯示在這裡。',
  'A previous export is still finishing. You can export again when it completes.': '先前的匯出仍在完成中，結束後即可再次匯出。',
  'Export was cancelled.': '匯出已取消。',
  'Unable to export the feedback session.': '無法匯出回饋工作階段。',
  'Include images': '包含圖片',
  'Close export dialog': '關閉匯出對話框',
  'Arrow Navigate': '方向鍵導覽',
  'Enter Edit': 'Enter 編輯',
  'Del Remove': 'Del 移除',
  'Drag Reorder': '拖曳重新排序',

  // Main status, history, review, and export surfaces.
  Processing: '處理中',
  'Processing…': '處理中……',
  'Recording...': '正在錄製……',
  'Processing...': '處理中……',
  'Recording!': '正在錄製！',
  Ready: '準備完成',
  'Copied to clipboard!': '已複製到剪貼簿！',
  'Error occurred': '發生錯誤',
  'just now': '剛剛',
  'Just now': '剛剛',
  'Untitled Session': '未命名工作階段',
  Open: '開啟',
  Screenshot: '螢幕截圖',
  'Session thumbnail': '工作階段縮圖',
  'Search sessions...': '搜尋工作階段……',
  Date: '日期',
  Name: '名稱',
  'Item Count': '項目數量',
  Duration: '時間長度',
  'No sessions found': '找不到工作階段',
  'No sessions yet': '目前沒有工作階段',
  'Try adjusting your search terms or clear the filter to see all sessions.': '請調整搜尋關鍵字，或清除篩選條件以查看所有工作階段。',
  'Start recording feedback to see your sessions here.': '開始錄製回饋後，工作階段會顯示在這裡。',
  'Clear Search': '清除搜尋',
  'Select All': '全選',
  'Move Up': '上移',
  'Move Down': '下移',
  'Delete confirmation': '刪除確認',
  'Feedback items': '回饋項目',
  'Keyboard shortcuts list': '鍵盤快速鍵清單',
  'Retry save': '重試儲存',
  'Markdown report preview': 'Markdown 報告預覽',
  'Deleted': '已刪除',
  'Finish or cancel the active edit before saving': '儲存前請先完成或取消目前的編輯',
  'click to edit': '點擊編輯',
  'Reorder': '重新排序',
  'Navigate': '導覽',
  'Edit': '編輯',
  'Remove': '移除',
  'Category': '類別',
  Bug: '錯誤',
  'UX Issue': '使用者體驗問題',
  Suggestion: '建議',
  Performance: '效能',
  Question: '問題',
  Critical: '嚴重',
  High: '高',
  Medium: '中',
  Low: '低',

  // Provider, local Whisper, and credential details.
  'OpenAI is an optional cloud transcription fallback. Report generation uses the provider and model selected above.': 'OpenAI 是選用的雲端轉錄備援。報告會使用上方選取的服務與模型產生。',
  'Managed model:': '管理中的模型：',
  'Runs through the companion CLI Bridge.': '會透過搭配使用的 CLI 橋接程式執行。',
  'Codex default': 'Codex 預設值',
  'Claude Code default': 'Claude Code 預設值',
  'OpenCode default': 'OpenCode 預設值',
  'Cursor default': 'Cursor 預設值',
  'Qwen default': 'Qwen 預設值',
  'Goose default': 'Goose 預設值',
  'Amp default': 'Amp 預設值',
  'Kiro default': 'Kiro 預設值',
  'Aider default': 'Aider 預設值',
  'Anthropic default': 'Anthropic 預設值',
  'Select an installed Ollama model': '選擇已安裝的 Ollama 模型',
  'Select an installed LM Studio model': '選擇已安裝的 LM Studio 模型',
  'Connect the App Store app to AI CLIs already installed and signed in on this Mac.': '將 App Store 版本連接到這台 Mac 上已安裝並登入的 AI 命令列工具。',
  'Confirm deletion': '確認刪除',
  'Click to confirm deletion': '點擊確認刪除',
  'Test Key': '測試金鑰',
  'Verified!': '已驗證！',
  'Saving…': '儲存中……',

  // Recording guidance, annotation, and processing states.
  Paused: '已暫停',
  Mic: '麥克風',
  issue: '個問題',
  issues: '個問題',
  Cue: '標記',
  Draw: '繪製',
  Done: '完成',
  'Annotation is unavailable for this capture': '這次擷取無法使用標註',
  'Choose Draw, mark the screen, then choose Done to save': '選擇「繪製」、標記螢幕，再選擇「完成」儲存',
  'Marked area ready · click to save and continue': '標記區域已準備完成 · 點擊以儲存並繼續',
  'Save this marked issue and return control to the screen': '儲存這個標記問題並將控制權交還螢幕',
  'Draw directly over the recorded area': '直接在錄製區域上繪製',
  'Finalizing recording assets...': '正在完成錄製素材……',
  'Transcribing narration...': '正在轉錄旁白……',
  'Analyzing spoken context...': '正在分析語音內容……',
  'Saving session artifacts...': '正在儲存工作階段檔案……',
  'Extracting key visual frames...': '正在擷取關鍵畫面……',
  'Generating markdown report...': '正在產生 Markdown 報告……',
  'Finalizing output files...': '正在完成輸出檔案……',
  'Finalizing report output...': '正在完成報告輸出……',
  'Transcribing audio...': '正在轉錄音訊……',
  'Using captured transcript (': '使用已擷取的逐字稿（',
  ' segments)': ' 個片段）',

  // First-run setup and permission guidance.
  'Get Started': '開始使用',
  'Skip setup, configure later': '略過設定，稍後再設定',
  'Welcome to MarkuprPlus': '歡迎使用 MarkuprPlus',
  'Capture developer feedback with voice narration and intelligent screenshots.': '使用語音旁白與智慧螢幕截圖記錄開發回饋。',
  'AI-ready documentation in seconds.': '幾秒內產生可供 AI 使用的文件。',
  'Allow Microphone Access': '允許麥克風權限',
  'Allow Screen Recording': '允許螢幕錄製權限',
  'Click "Open System Settings" below': '點擊下方的「開啟系統設定」',
  'Find "MarkuprPlus" in the list': '在清單中找到「MarkuprPlus」',
  'Click "Check Again" to verify': '點擊「再次檢查」進行確認',
  'Screen recording enabled! MarkuprPlus can now capture screenshots.': '螢幕錄製已啟用！MarkuprPlus 現在可以擷取螢幕畫面。',
  'Note: You may need to restart MarkuprPlus after enabling.': '注意：啟用後可能需要重新啟動 MarkuprPlus。',
  'Start Your First Recording': '開始第一次錄製',
  'Skip for now — use local transcription': '暫時略過 — 使用本機轉錄',
  'Skip — configure report generation later': '略過 — 稍後設定報告產生',
  'Search shortcuts': '搜尋快速鍵',
  'No shortcuts match': '沒有符合的快速鍵',

  // Window picker and update notifications.
  'Choose a screen or window, then start recording': '選擇螢幕或視窗，然後開始錄製',
  'Unable to find any screens or windows to capture.': '找不到可擷取的螢幕或視窗。',
  'Please check your screen recording permissions.': '請檢查螢幕錄製權限。',
  'Collapse release notes': '收合版本說明',
  'Expand release notes': '展開版本說明',
  'Version is ready to install': '版本已準備好安裝',
  'Install Update': '安裝更新',
  'Check for Updates': '檢查更新',

  // Miscellaneous errors and accessibility labels.
  'Unable to save review.': '無法儲存回饋編輯內容。',
  'This shortcut cannot be customized.': '這個快速鍵無法自訂。',
  'The hotkey registration result was invalid.': '快速鍵註冊結果無效。',
  'Unable to register this shortcut.': '無法註冊這個快速鍵。',
  'The registered shortcut did not match the saved setting.': '已註冊的快速鍵與儲存的設定不一致。',
  'Unable to save this shortcut.': '無法儲存這個快速鍵。',
  'Shortcut saving is unavailable.': '目前無法儲存快速鍵。',
  'Unknown screen recording error.': '未知的螢幕錄製錯誤。',
  'Unable to start session.': '無法開始工作階段。',
  'Unknown session error.': '未知的工作階段錯誤。',
  'Unable to stop session.': '無法停止工作階段。',
  'Unable to resume session.': '無法繼續工作階段。',
  'Unable to pause session.': '無法暫停工作階段。',
  'Pause/resume failed.': '暫停／繼續失敗。',
  'Manual capture failed.': '手動擷取失敗。',
  'Unable to change annotation mode.': '無法變更標註模式。',
  'The saved report folder is unavailable.': '儲存的報告資料夾無法使用。',
  'Unable to save review changes.': '無法儲存回饋編輯變更。',
  'Recover Previous Session?': '要復原上一個工作階段嗎？',
  'Show details': '顯示詳細資料',
  'Hide details': '隱藏詳細資料',
  'Has screenshot': '有螢幕截圖',
  'Not included': '未包含',
  'Discard': '捨棄',
  'Discarding...': '捨棄中……',
  'Recover Session': '復原工作階段',
  'Recovering...': '復原中……',
};

const FRAGMENT_TRANSLATIONS: Array<[string, string]> = [
  ['Welcome to ', '歡迎使用 '],
  [' and intelligent screenshots.', ' 與智慧螢幕截圖。'],
  ['MarkuprPlus needs microphone access to transcribe your voice narration as you', 'MarkuprPlus 需要麥克風權限，才能在你'],
  ['walk through your feedback.', '講述回饋時轉錄你的語音。'],
  ['Your audio is processed locally and securely.', '你的音訊會在本機安全地處理。'],
  ['MarkuprPlus records the selected screen or window and saves each marked area with', 'MarkuprPlus 會錄製選取的螢幕或視窗，並將每個標記區域與'],
  ['the narration that explains it.', '說明內容的旁白一起儲存。'],
  ['Grant Screen Recording permission to enable video,', '授予螢幕錄製權限即可啟用影片、'],
  ['screenshots, and live markup.', '螢幕截圖與即時標註。'],
  ['Because MarkuprPlus uses a new app identity, an upgrade', '由於 MarkuprPlus 使用新的應用程式識別，升級時'],
  ['may ask you to grant Screen Recording, Microphone, and Accessibility permissions again.', '可能會再次要求你授予螢幕錄製、麥克風與輔助使用權限。'],
  ['MarkuprPlus is ready. Press ', 'MarkuprPlus 已準備完成。按下 '],
  [' to start,', ' 開始，'],
  ['then speak naturally.', '然後自然地說話。'],
  ['and drag to mark the current screen.', '並拖曳標記目前的螢幕。'],
  ['Release the key, then click normally to save and', '放開按鍵，再正常點擊以儲存並'],
  ['clear that issue while the click still reaches the app underneath.', '清除該問題，同時點擊仍會傳遞給下方的應用程式。'],
  ['Repeat for', '重複此操作，直到'],
  ['as many separate issues as you need.', '你需要的多個獨立問題。'],
  [' uses OpenAI for post-session narration transcription. Create an API key at ', ' 使用 OpenAI 進行工作階段結束後的旁白轉錄。請在此建立 API 金鑰：'],
  ['(or skip and configure local transcription later).', '（或略過，稍後再設定本機轉錄）。'],
  ['—or use ', '—或使用 '],
  [' later in Settings ', '，稍後可在設定 '],
  ['(or skip and configure in Settings > Advanced later).', '（或略過，稍後在「設定 > 進階」中設定）。'],
  ['Ready · ', '準備完成 · '],
  ['Managed model: ', '管理中的模型：'],
  ['Download the managed ', '下載管理中的 '],
  [' model for automatic local transcription.', ' 模型以自動進行本機轉錄。'],
  ['Runs through the companion CLI Bridge.', '會透過搭配使用的 CLI 橋接程式執行。'],
  ['Sort: ', '排序：'],
  ['shots marked', '畫面已標記'],
  [' shots marked', ' 個畫面已標記'],
  [' shots', ' 個畫面'],
  [' items', ' 個項目'],
  [' selected', ' 已選取'],
  ['sessions', '個工作階段'],
  ['m ago', '分鐘前'],
  ['h ago', '小時前'],
  ['d ago', '天前'],
  [' days', ' 天'],
  [' hours', ' 小時'],
  [' minutes', ' 分鐘'],
  ['More actions for feedback ', '更多回饋操作 '],
  ['Feedback actions for ', '回饋操作：'],
  ['Deleted ', '已刪除 '],
  ['Screenshot ', '螢幕截圖 '],
  ['Arrow (', '箭頭（'],
  ['Circle (', '圓形（'],
  ['Rectangle (', '矩形（'],
  ['Freehand (', '自由繪製（'],
  ['Text (', '文字（'],
  [' and drag to mark · click to save and continue', ' 並拖曳以標記 · 點擊以儲存並繼續'],
  ['Hold ', '按住 '],
  ['Mark Shot: ', '標記畫面：'],
  ['Stop: ', '停止：'],
  ['Pause: ', '暫停：'],
  ['Cue ', '標記 '],
  ['to navigate', '以導覽'],
  ['to select', '以選取'],
  ['to cancel', '以取消'],
  ['showing latest ', '顯示最近 '],
  ['Version ', '版本 '],
  [' is ready to install', ' 已準備好安裝'],
  ['This will permanently delete the session', '這會永久刪除這個工作階段'],
  [' and all associated screenshots.', '，以及所有相關螢幕截圖。'],
  ['This action cannot be undone.', '此操作無法復原。'],
  ['Discarding will permanently delete this session data.', '捨棄後會永久刪除這個工作階段的資料。'],
  ['Recovery will save your feedback and committed marked issues as a report.', '復原會將你的回饋與已確認的標記問題儲存成報告。'],
  ['...and ', '……還有 '],
  [' more', ' 個'],
  ['Processing ', '處理中 '],
  ['Press ', '按下 '],
  [' to continue', ' 以繼續'],
  [' to skip', ' 以略過'],
  [' to recover', ' 以復原'],
  [' to discard', ' 以捨棄'],
  [' to navigate', ' 以導覽'],
  [' to select', ' 以選取'],
  [' to cancel', ' 以取消'],
  [' to edit', ' 以編輯'],
  [' to remove', ' 以移除'],
  ['Arrow keys', '方向鍵'],
  ['No sources available', '沒有可用的來源'],
  ['Screen recording unavailable', '螢幕錄製無法使用'],
  ['Timed out waiting for the selected capture source.', '等待所選擷取來源逾時。'],
  ['Session Error', '工作階段錯誤'],
  ['Start a session', '開始工作階段'],
  ['Run a session', '執行工作階段'],
  ['Local Whisper', '本機 Whisper'],
  ['OpenAI Whisper', 'OpenAI Whisper'],
  ['Download required', '需要下載'],
  ['API Key', 'API 金鑰'],
  ['API key', 'API 金鑰'],
  ['Enter your ', '輸入你的 '],
  [' API key', ' API 金鑰'],
  [' accent color', ' 強調色'],
  ['Current theme: ', '目前主題：'],
  ['Theme: ', '主題：'],
  ['Click to toggle', '點擊切換'],
  ['click to toggle', '點擊切換'],
  ['Processing ', '處理中 '],
  [' complete', ' 完成'],
  ['Retry Export as ', '再次匯出為 '],
  ['Export as ', '匯出為 '],
  [' feedback items', ' 個回饋項目'],
  ['Rebind ', '重新設定 '],
  [' to recover or', ' 以復原，或'],
  ['Draw to annotate | Press ', '繪製以標註｜按下 '],
  [' tools | ', ' 工具｜'],
  [' to undo', ' 以復原'],
];

export const traditionalChineseCatalog: UiTranslationCatalog = {
  exact: EXACT_TRANSLATIONS,
  fragments: FRAGMENT_TRANSLATIONS,
};
